### ISSUE TITLE
Navigation with the page pattern

### ISSUE THREAD

**Issue by ghost** [icnocop/cuite#100]
I have been hunting around for a CUTEe sample, but not much luck on the net, codeplex, samples or git issues.

I would like to use the page object to inplement the page pattern, but I am unsure where navigation belongs.  I have seen two examples where the author has write a custom method in a page object that does a "NavigateTo" and returns another page object.  This introduces a coupling between two pages, which (may or may not) be a good idea when an web app requires maintenance on hundreds of pages.

What other ways can pages be used and have the page navigation isolated from the page object?

thanks.

**Comment by FantasticFiasco** [comment]
CUITe is currently in 2.0 pre-release due to numerous issues, whereas better documentation of the new features is one. At the moment the best chance of figuring out how a certain feature is supposed to work is by looking at the tests.

CUITe is opinionated in the way that it encourages navigation to be a part of the page object pattern, thus introducing coupling between pages as you describe. The [PageObject article](http://martinfowler.com/bliki/PageObject.html) by Martin Fowler states:

_"Similarly if you navigate to another page, the initial page object should return another page object for the new page [2]._

but he also states:

_"However some practitioners prefer that page objects return some generic browser context, and the tests control which page objects to build on top of that context based on the flow of the test (particularly conditional flows)."_

As you've found out, CUITe has implemented navigation to work as the first quote, not the second.

One would assume that even though you have hundred of pages, not all link to each other. Usability enforces good workflows between the pages, and those workflows shouldn't be hard to implement using the page object pattern together with navigation.

Or am I wrong?

**Comment by ghost** [comment]
Thanks for the quick reply.

We'll stick with the prescribed navigation and page coupling in the page object.

Yes, implementing navigation in the page objects will probably be straight forward.  But for us and our large website, we are focusing on maintenance.  Any place we can see to reduce maintenance effort we will.
