### ISSUE TITLE
Integrate with a continuous integration (build) server

### ISSUE THREAD

**Issue by icnocop** [icnocop/cuite#18]
Integrate with TeamCity Continuous Integration (Build) Server

**Comment by FantasticFiasco** [comment]
I'm running TeamCity on my home server. If you experience any problems with TC or how to configure it in IIS please ask. Sorry if this came across as being a show-off, I'm not. I just wanted to let you know that if you ever come across any problems with configuring TC or IIS, please ask.

I am running my instance of TC using port mappings in IIS using a host name I own. Thus I am able to connect to my server on port 80 with a known hostname, and IIS redirects all traffic to a local port TC is using on my server.

**Comment by icnocop** [comment]
While I wait for the teamcity.codebetter.com registration to complete, I went ahead and created build instructions on appveyor [here](https://ci.appveyor.com/project/icnocop/cuite).

The build script defined in the CI build is simply:

```
call "%VS120COMNTOOLS%VsDevCmd.bat"
msbuild.exe src\build.proj /t:Build;Pack
```

I'm currently getting the error:

```
ObjectRepository\SlTestPage.cs(14,32): error CS0012: The type 'Microsoft.VisualStudio.TestTools.UITesting.SilverlightControls.SilverlightControl' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.VisualStudio.TestTools.UITest.Extension.Silverlight, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [C:\projects\cuite\src\Sample_CUITeTestProject\Sample_CUITeTestProject.csproj]
```

**Comment by FantasticFiasco** [comment]
Isn't that because the plugin _Microsoft Visual Studio 2013 Coded UI Test Plugin for Silverlight_ is missing from the server where the CI is running?

In the readme we state that the plugin is mandatory for development of CUITe, that's why I didn't have the Silverlight references locally in the Thirdparty directory.

I guess the solution would be to not force the developers to install the plugin, but instead commit the Silverlight assemblies in the _Thirdparty_ directory, as we do with the CUIT assemblies? Developers then didn't have to install the plugin and the CI would be happy.

**Comment by FantasticFiasco** [comment]
Sorry, sorry sorry. It is rather late in my time zone and I am getting sleepy. The reason is that only the project _CUITe_ has been configured to be built for different versions. If you take a look at the csproj file you'll see the following text:

```
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '10'">
      <ItemGroup>
        ...
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Extension.Silverlight, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
          <HintPath>..\ThirdParty\CUIT\v10\Microsoft.VisualStudio.TestTools.UITest.Extension.Silverlight.dll</HintPath>
        </Reference>
      </ItemGroup>
    </When>
    <When Condition="'$(VisualStudioVersion)' == '11'">
      <ItemGroup>
        ...
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Extension.Silverlight, Version=11.0.0.0, Culture=neutral, PublicKeyToken=374b4c93160c098c, processorArchitecture=MSIL">
          <Private>False</Private>
          <HintPath>..\ThirdParty\CUIT\v11\Microsoft.VisualStudio.TestTools.UITest.Extension.Silverlight.dll</HintPath>
        </Reference>
      </ItemGroup>
    </When>
    <When Condition="'$(VisualStudioVersion)' == '12'">
      <ItemGroup>
        ...
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Extension.Silverlight, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
          <HintPath>..\ThirdParty\CUIT\v12\Microsoft.VisualStudio.TestTools.UITest.Extension.Silverlight.dll</HintPath>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

The other projects aren't configured this way, they don't specify a HintPath for the Silverlight assembly, and it is then assumed to be installed in a path that is known by VS. What we can do is configure the other projects the same way _CUITe_ is configured.

Do you wish me to create a PR? The configuration should be extracted to a new file, and the file should be referenced by the projects.

**Comment by icnocop** [comment]
Builds are succeeding and nuget packages are automatically being published to nuget.org https://ci.appveyor.com/project/icnocop/cuite
