### ISSUE TITLE
Consolidate solutions and projects

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#2]
There are far to many solutions and projects in the source code, and synchronizing these is error prone.

When it comes to the solution I think the maintainer should decide on one Visual Studio version. I would propose Visual Studio 2013, and if no major bug is discovered in the upcoming month in Visual Studio 2015, move over to that version.

Regarding the projects I think the maintainer can use different project configurations to decide which .NET version to target. I've done so to [MVVM Dialogs](https://github.com/FantasticFiasco/mvvm-dialogs) with great success.

**Comment by FantasticFiasco** [comment]
I would like to start with this one before moving on to NuGet. I don't have VS2010 installed and would't want to install it. Using only one version of Visual Studio will only benefit contributes. What do you think about it?

**Comment by icnocop** [comment]
Microsoft's Coded UI Test assemblies are not backward compatible.

For example, if you build CUITe in Visual Studio 2013 and try to use the assemblies in Visual Studio 2010 or 2012, then I've found that either the tests do not show up in the test explorer or an "assembly not found" error occurs during runtime for example.

That's one reason why there is a solution for each version of Visual Studio.

There's also project for each targeted version of .NET but the source code files are shared/linked which makes it easier to maintain the project references instead of manually editing the csproj files for example.

We can decide to drop support for a specific version but I'm not sure how that would affect the community (myself included) who are still using .NET 3.5 on Windows XP for automated UI testing for example, which White/TestStack no longer supports.

What I would suggest is to just update the solutions/projects/source code that you need and then I will try to keep things backward compatible with older versions.

Thank you.

**Comment by FantasticFiasco** [comment]
I agree with the fact that we shouldn't drop support for any Visual Studio version, nor any .NET version. That is unacceptable. I think we should support all variants of versions.

I think we can solve the Visual Studio issue with assembly redirects (because the CUIT assemblies are located in the Visual Studio versioned path), and the .NET version issue could be solved with conditions in the project files.

Do you have the relevant Visual Studio versions installed? When there is a pull request ready we have to verify that I didn't mess anything up.

**Comment by icnocop** [comment]
Yes, I have all the relevant Visual Studio versions installed.

Thank you.

**Comment by FantasticFiasco** [comment]
Can you help me with what versions of .NET and Visual Studio CUITe is supporting. I've filled in the supported .NET versions of .NET VS2010 and VS2013, but would like some help with filling in the versions VS2012 are supporting.

|  | .NET 3.5 | .NET 4.0 | .NET 4.5 |
| --- | :-: | :-: | :-: |
| Visual Studio 2010 | x | x |  |
| Visual Studio 2012 | ? | ? | ? |
| Visual Studio 2013 | x | x | x |

I've added VS2010 here as well since you mentioned that .NET3.5 was supported, but I don't see that in the code or the projects existing. In fact this [link](http://stackoverflow.com/questions/13720550/coded-ui-test-net-frameworks-supported) says that .NET3.5 isn't supported. Can you please clarify the issue for me?

**Comment by FantasticFiasco** [comment]
Bump

**Comment by icnocop** [comment]
[Supported Configurations and Platforms for Coded UI Tests and Action Recordings (Visual Studio 2010)](https://msdn.microsoft.com/en-us/library/dd380742%28v=vs.100%29.aspx)

[Supported Configurations and Platforms for Coded UI Tests and Action Recordings (Visual Studio 2012)](https://msdn.microsoft.com/en-us/library/dd380742%28v=vs.110%29.aspx)

[Supported Configurations and Platforms for Coded UI Tests and Action Recordings (Visual Studio 2013)](https://msdn.microsoft.com/en-us/library/dd380742%28v=vs.120%29.aspx)

[Supported Configurations and Platforms for Coded UI Tests and Action Recordings (Visual Studio 2015)](https://msdn.microsoft.com/en-us/library/dd380742%28v=vs.140%29.aspx)

CUITe can support the same configurations and platforms as CUIT, but that isn't the case currently.

The build script in the latest code only builds the following:
CUITe for .NET v4 (VS2010)
CUITe for .NET v4 (VS2012)
CUITe for .NET v4.5 (VS2012)
CUITe for .NET v4 (VS2013)
CUITe for .NET v4.5 (VS2013)

**Comment by FantasticFiasco** [comment]
Thanks for the information.

The build scripts are then correct I think. Coded UI tests can only be created in .NET4.0 or .NET4.5 assemblies, while they can **test** an application built with as low as .NET2.0, at least that is what I get from the links. And I now realize what you meant with support for Windows XP. VS2010 is the only version of Visual Studio that can target that OS, got it.

One question about the _CUITe_ObjectRecorder_ project. Is that built with x86 since most users run Internet Explorer as a 32-bit process?

**Comment by FantasticFiasco** [comment]
Do you know why Silverlight isn't supported in VS2013 .NET4.0? There is a define called _SILVERLIGHT_NOT_SUPPORTED_ that exclude Silverlight support for that specific combination.

**Comment by icnocop** [comment]
The CUITe_ObjectRecorder project targets the x86 platform because it's compatible with both 32-bit and 64-bit operating systems.

There wasn't a need to have support for a 64-bit specific version.

SILVERLIGHT_NOT_SUPPORTED was implemented before the [Microsoft Visual Studio 2013 Coded UI Test Plugin for Silverlight](https://visualstudiogallery.msdn.microsoft.com/51b4a94a-1878-4dcc-81e0-7dc92131d2da) was released.

**Comment by FantasticFiasco** [comment]
Thanks for the quick merge, I am really impressed with the support you are giving this project.

**Comment by icnocop** [comment]
Thank you very much for contributing! :)

**Comment by FantasticFiasco** [comment]
Should we close this issue? I am not expecting more information from you, do expect information from me?
