### ISSUE TITLE
CUITe tests not discovered in VS2015

### ISSUE THREAD

**Issue by Kritner** [icnocop/cuite#30]
Tests are not running in VS2015, I have included the "specific version" of the testing DLLs from successful runs in VS2012. Tests seem discovered, but are not running with the following in the output window:

> There is no test with the specified Id (guid listed)

An additional issue that appears to occur when I do not copy over the specific UnitTesting dlls from VS2012's versions of the test DLLs is:

> Warning: Unable to load types from the test source 'H:\Test***_.dll'. Some or all of the tests in this source may not be discovered. If you are running unit tests for Windows Store apps and referencing custom WinMD type then please visit http://go.microsoft.com/fwlink/?LinkId=238340 for more info. Error details: System.IO.FileNotFoundException: Could not load file or assembly 'M
> icrosoft.VisualStudio.TestTools.UITesting, Version=11.0.0.0, Culture=neutral, Pu
> blicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot fin
> d the file specified.
> .
> Warning: MSTestAdapter failed to discover tests in class 'SmokeTest.CodedUITest1' of assembly 'H:\Test\**_*.dll'. Reason Could not load file or assembly Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..

I'm assuming this is due to CUITe being targeted at specific microsoft unit testing DLLs and CUITe has not yet been given build steps/definition for VS2015's version of said DLLs?  Only guessing there, I really have no idea what I'm talking about :O.

**Comment by FantasticFiasco** [comment]
We should probably move over to VS2015 when you are ready icnocop. A new NuGet package needs to be created as well, I guess that affects the CI build scripts?

Let me know when, and I'll start working on it.

**Comment by Kritner** [comment]
@FantasticFiasco I put in a pull request for VS2015 that at least gets the solution building via "Rebuild" from VS2015, still having issues with Build.bat though.  I know it's not much, but I couldn't get much further as I only have VS2015 community at home - did the csproj updates from work where I have access to UI test tools.  

I was not able to test if the successfully built CUITe.dll worked with my test, as my tests were built off of the codePlex version of the code, which seems to have significant API changes from this version.

**Comment by FantasticFiasco** [comment]
@Kritner I took a quick glance at your PR and you came very close to completion. There are a couple of things to do in the PR, but nothing big. Nice work!

I can help you complete the PR when the maintainer gives the green light.

**Comment by icnocop** [comment]
Yes, I think having support for Visual Studio 2015 will be great! I should be able to update the CI build script without issue. Thank you!

**Comment by FantasticFiasco** [comment]
My current week is pretty hectic, I might not get the chance to look at it until next week. One thing I know is that a Silverlight plugin for VS2015 hasn't been released which might pose a problem. We might end up in a situation where both VS2013 and VS2015 needs to be installed.

**Comment by FantasticFiasco** [comment]
@icnocop I've been thinking about upgrading to VS2015 and the problems we have with the Silverlight plugin not being released yet. The fact that we are depending on a thirdparty that we have no control over is a problem for the project.

I've been going over and over in my head what you said about breaking out the Silverlight parts, thus not forcing customers to install the Silverlight plugin if they aren't using Silverlight, but also making it possible for us to continue working with HTML/WinForms/WPF/Telerik support even if we cannot support newer VS versions when it comes to Silverlight.

I am mentioning this in relation to the VS2015 support because if we move the Silverlght support to a new assembly, there is possibly an opening for creating only one HTML/WinForms/WPF/Telerik NuGet package that supports all VS versions. I was unable to do so in the past because assembly redirects are only possible when the different versions of the assembly share the same public key token. For some reason the Silverlight plugin developers decided to change the public key token when releasing newer versions of the plugin.

This would mean that we would have one NuGet package for the HTML/WinForms/WPF/Telerik support, and  a couple of NuGet packages supporting Silverlight for different VS versions. Since we haven't released a official NuGet package yet I think this is the time, if ever, to make this change. When we've released our first official NuGet packages we are kind of stuck with that design.

I would like to do a spike regarding this and would love to hear you thought regarding the issue.

Sorry for the long post.

**Comment by icnocop** [comment]
Yes, I think having separate NuGet packages like you've indicated is best. 

Thank you.

**Comment by FantasticFiasco** [comment]
I am closing in on the complete solution now. We will be able to support all VS versions from one NuGet package when it comes to HTML/Telerik/WinForms/WPF. Since the Silverlight plugin hasn't been released for VS2015, we as developers still have to use VS2013 even though CUITe supports VS2015.

The other alternative would be to have two solutions: one VS2013 containing the Silverlight code and one VS2015 containing the rest, i.e. we would still have to use VS2013 for Silverlight support. I think we perhaps can stay on VS2013 until (if ever) the Silverlight plugin is released for VS2015, and then move up.

What are your thoughts?

**Comment by icnocop** [comment]
I'm fine with either approach.  If the silverlight plugin is ever released for VS2015, then yes, we can move up. But also, if/when there's another reason to move to VS2015, then we can separate the silverlight code in its own VS2013 solution and carry the rest forward. Thank you.
