### ISSUE TITLE
Expand component modeling

### ISSUE THREAD

**Issue by spelltwister** [icnocop/cuite#59]
I wasn't sure how else to reach you, but I wish I had noticed you updated the CUITe to include new types.  I also spent time last year creating CodedUI Fluent Extensions because I didn't realize this project existed at the time.  The primary purpose for creating that was to enhance the modeling system and abstract away the underlying technology into behavior such as clicking and setting values.  You have some abstraction around ViewComponents and such, but I would like to bring in some of the page modeling stuff to CUITe.

I'm going to do a small implementation of my page modeling interfaces using CUITe to see if that's something you'd be interested in pulling into the project.

**Comment by FantasticFiasco** [comment]
Hi.

I'll fork your repo and have a look at the code. I often find it easier to see the usage of the framework by reading the tests, or perhaps you know some project that is using _CodedUI Fluent Extensions_ that I can take a look at?

Thank you for contacting us, we always encourage participation.

**Comment by spelltwister** [comment]
I have minimal testing included in the project, but the extensions are being used on a closed source project with a fair amount of success.

From the example on your information page,

// Launch the web browser and navigate to the homepage
BrowserWindowUnderTest browserWindow = BrowserWindowUnderTest.Launch("https://website.com");

var pageModel = new FirstNameLastNameFormModel(browserWindow);
Assert.IsTrue(pageModel.Save.IsNotActionable(0)); // should be disabled until fields are entered

pageModel.FirstName.SetText("John");
Assert.IsTrue(pageModel.Save.IsNotActionable(0)); // should be disabled until fields are entered

pageModel.LastName.SetText("Doe");
Assert.IsTrue(pageModel.Save.IsActionable(0)); // should be enabled after fields are entered

var nextPageModel = pageModel.Save.Click();
Assert.IsTrue(pageModel.ErrorMessageArea.CanNotFind(1000)); // no error box should appear

The point is to avoid putting specific technology elements into the test so that if the Save button changes to a hyperlink, the test would not change, you just change the model implementation (eg, FirstNameLastNameFormModel's Save property would find HtmlHyperlink instead.)  Imagine Save being called in hundreds of tests.  Updating the model implementation is much simpler.

**Comment by FantasticFiasco** [comment]
What you call _Page Models_, CUITe calles _Page Components_, and [Martin Fowler](http://martinfowler.com/bliki/PageObject.html) (and probably all other because of this) calls _Page Objects_. I've thought about renaming the CUITe classes to conform with what Martin Fowler thinks but haven't got around to do the implementation.

Regarding the sample code you demostrated, I would much rather see that it used the `Page` class instead of `BrowserWindowUnderTest`.

``` c#
var mainPage = Page.Launch<MainPage>("https://website.com");
```

Regarding full sample, see the tests in the _Sut.Html.PageComponentsTest_. It uses both the page component classes and the object repository pattern that CUITe features.

Other than that, you seem to have implemented a couple of features CUITe doesn't have, and we would be very happy if you decided to contribute. If there is anything I can help you with, please feel free to ask.

**Comment by FantasticFiasco** [comment]
@spelltwister Is it OK if we close this issue?
