### ISSUE TITLE
Port readme.txt to README.md

### ISSUE THREAD

**Issue by FantasticFiasco** [icnocop/cuite#6]
GitHub heavily relies in the README.md. Port the text from _readme.txt_ to _README.md_. MD is short for _Markdown_ and [here](https://help.github.com/articles/github-flavored-markdown/) is a good introduction to its syntax.

**Comment by icnocop** [comment]
I've updated README.md with more information than just readme.txt, as this is the first thing users usually see. I hope it's not too much information, but just enough so they can get familiar with CUITe and know how to install and start using it right away.

**Comment by FantasticFiasco** [comment]
Nice work! It sure is a trade-off between to much information and to little information. When I get around I'll also help with writing some of the Wiki-pages as well. They can serve as the more elaborate source of information while the readme just gives you the highlights.

Something that blew my mind on the CodePlex site was the fact that CUITe was mentioned on Channel9, But your thoughts are perhaps that the CodePlex site still have enormous value in terms of discussions and issues, and I couldn't argue with you on that.

Do you wan't me to close this issue or keep it open?

**Comment by icnocop** [comment]
Yes, I like the fact that CUITe was mentioned on Channel9 too. :)

And yes, I think the codeplex site still has value.

I want to update the codeplex site to indicate that the code has moved to github, but the only missing piece is that github doesn't have a discussion forum where users can ask questions or get help, etc.

So it seems we have several options:
a. Keep using the old codeplex site for discussions
b. Use github issues like a discussion forum
c. Create a separate discussion forum (ex. google groups, stackoverflow, or disqus)

I think I like option b the best because there's only one place we need to search for things.

What are your thoughts?

Thank you.

**Comment by FantasticFiasco** [comment]
I did a quick search on CodePlex to see what other project have done.

**.NET Compiler Platform ("Roslyn")**
Indicating move in text. Discussions still open.

**Unity.MVC3**
Indicating move in title and in text. Discussions closed.

**Log4j JNA-based Appenders**
Indicating move in title and in text. Discussions open but referring to GitHub.

**BugNET Issue Tracker**
Indicating move in title and in text. Discussions moved to GitHub issues.

I also prefer _b_ as an alternative, but with a bit of _a_ mixed in. I don't mind answering questions in the discussions of CodePlex (my handle on CodePlex BTW is Disore). When it comes to issues I think we politely can ask for the issue on GitHub instead.

One thing to keep in mind is that CUITe on CodePlex still is the top search result when Googling for _CUITe_, i.e. there will be trafic to the CodePlex site.

**Comment by icnocop** [comment]
Thank you for your quick feedback.

I've updated the codeplex site to indicate that CUITe has moved to github in multiple places (home, downloads, documentation, and discussions).

Let me know if you'd like me to make any changes to the codeplex site as I am always open for changes.

Thank you! :)
